export const TODAY_LOADING = 'TODAY_LOADING'
export const TODAY_SUCCESS = 'TODAY_SUCCESS'
export const TODAY_FAILED  = 'TODAY_FAILED'

export const FORECAST_LOADING = 'FORECAST_LOADING'
export const FORECAST_SUCCESS = 'FORECAST_SUCCESS'
export const FORECAST_FAILED  = 'FORECAST_FAILED'